name: Release
run-name: ${{ github.ref_name }} Release

on:
  push:
    branches:
      - main
      - alpha

jobs:
  call-test-workflow:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/test-flow.yaml
    with:
      from: ${{ github.workflow }}
      templatePrefix: ${{ github.workflow }}
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs: call-test-workflow
    steps:
      # Use our auto-commit permissioned app for our git actions
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.AUTO_COMMIT_APP_ID }}
          private-key: ${{ secrets.AUTO_COMMIT_APP_PKEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
